version: "3.8"

services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - seo_network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
       - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/seo-audit
    depends_on:
      - mongodb
    networks:
      - seo_network

  frontend:
    build:
      context: ./frontend
      args:
        # Docker mein empty string — nginx handle karega
        - VITE_API_URL=
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - seo_network

volumes:
  mongo_data:

networks:
  seo_network:
    driver: bridge